Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[18/Nov/2020 00:46:11] "GET / HTTP/1.1" 200 5518
Forbidden: /empressa/
[18/Nov/2020 00:46:32] "GET /empressa/ HTTP/1.1" 403 5132
[18/Nov/2020 00:46:34] "GET /api-auth/login/?next=/empressa/ HTTP/1.1" 200 2710
[18/Nov/2020 00:46:41] "POST /api-auth/login/ HTTP/1.1" 200 2948
[18/Nov/2020 00:46:47] "POST /api-auth/login/ HTTP/1.1" 302 0
/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'empressa_api.models.Empressa'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[18/Nov/2020 00:46:47] "GET /empressa/ HTTP/1.1" 200 10034
Forbidden: /empressa/
[18/Nov/2020 00:49:44] "GET /empressa/ HTTP/1.1" 403 58
[18/Nov/2020 00:50:36] "GET / HTTP/1.1" 200 5518
[18/Nov/2020 00:50:36] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[18/Nov/2020 00:50:36] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[18/Nov/2020 00:50:36] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[18/Nov/2020 00:50:36] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[18/Nov/2020 00:50:36] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[18/Nov/2020 00:50:36] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[18/Nov/2020 00:50:36] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[18/Nov/2020 00:50:36] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[18/Nov/2020 00:50:36] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[18/Nov/2020 00:50:36] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[18/Nov/2020 00:50:36] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[18/Nov/2020 00:50:37] "GET /favicon.ico HTTP/1.1" 404 4090
Forbidden: /empressa/
[18/Nov/2020 00:52:55] "GET /empressa/ HTTP/1.1" 403 5132
Forbidden: /usuario/
[18/Nov/2020 00:53:02] "GET /usuario/ HTTP/1.1" 403 5102
[18/Nov/2020 15:15:29] "GET / HTTP/1.1" 200 5518
[18/Nov/2020 15:15:29] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[18/Nov/2020 15:15:29] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[18/Nov/2020 15:15:29] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[18/Nov/2020 15:15:29] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[18/Nov/2020 15:15:29] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[18/Nov/2020 15:15:29] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[18/Nov/2020 15:15:29] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[18/Nov/2020 15:15:29] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[18/Nov/2020 15:15:29] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[18/Nov/2020 15:15:29] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[18/Nov/2020 15:15:29] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[18/Nov/2020 15:15:30] "GET /favicon.ico HTTP/1.1" 404 4090
[19/Nov/2020 18:29:56] "GET / HTTP/1.0" 200 99
[19/Nov/2020 19:47:53] "GET / HTTP/1.1" 200 95
[19/Nov/2020 19:47:54] code 400, message Bad request version ('ÑÎÙzv´Ï0t>¹>\x00\x00Ú\x00\x05\x00\x04\x00\x02\x00\x01\x00\x16\x003\x009\x00:\x00\x18\x005\x00')
[19/Nov/2020 19:47:54] You're accessing the development server over HTTPS, but it only supports HTTP.

[19/Nov/2020 19:47:54] "GET / HTTP/1.1" 200 95
[19/Nov/2020 21:39:12] "GET / HTTP/1.0" 200 95
[19/Nov/2020 22:08:58] "GET / HTTP/1.1" 200 5518
[19/Nov/2020 22:08:58] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[19/Nov/2020 22:08:58] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[19/Nov/2020 22:08:58] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[19/Nov/2020 22:08:58] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[19/Nov/2020 22:08:59] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[19/Nov/2020 22:08:59] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[19/Nov/2020 22:08:59] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[19/Nov/2020 22:08:59] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[19/Nov/2020 22:08:59] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[19/Nov/2020 22:08:59] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[19/Nov/2020 22:08:59] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
/opt/app_api_Pi/api/empressa_api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2020 - 00:45:54
Django version 2.2.17, using settings 'api.settings'
Starting development server at http://192.168.168.75:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/app_api_Pi/api/api/urls.py", line 20, in <module>
    from empressa_api import views
  File "/opt/app_api_Pi/api/empressa_api/views.py", line 6, in <module>
    from rest_framework_api_key.permissions import HasAPIKey
ImportError: No module named 'rest_framework_api_key'

/opt/app_api_Pi/api/api/settings.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 933, in _sanity_check
ValueError: Empty module name

/opt/app_api_Pi/api/api/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'rest'

/opt/app_api_Pi/api/api/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/registry.py", line 95, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: rest_framework

/opt/app_api_Pi/api/api/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'rest_framework_api_'

/opt/app_api_Pi/api/api/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'rest_framework_api_key'

/opt/app_api_Pi/api/api/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'rest_framework_api_key'

/opt/app_api_Pi/api/api/settings.py changed, reloading.
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/app_api_Pi/api/api/settings.py", line 64, in <module>
    API
NameError: name 'API' is not defined
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[19/Nov/2020 22:57:11] "GET /admin/empressa_api/empressa/ HTTP/1.1" 200 4618
[19/Nov/2020 22:57:11] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[19/Nov/2020 22:57:23] "GET /admin/empressa_api/empressa/1/change/ HTTP/1.1" 302 0
[19/Nov/2020 22:57:24] "GET /admin/login/?next=/admin/empressa_api/empressa/1/change/ HTTP/1.1" 200 1881
[19/Nov/2020 22:57:24] "GET /static/admin/css/login.css HTTP/1.1" 200 1233
[19/Nov/2020 22:57:31] "POST /admin/login/?next=/admin/empressa_api/empressa/1/change/ HTTP/1.1" 302 0
[19/Nov/2020 22:57:32] "GET /admin/empressa_api/empressa/1/change/ HTTP/1.1" 200 6841
[19/Nov/2020 22:57:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[19/Nov/2020 22:57:37] "GET /admin/empressa_api/ HTTP/1.1" 200 2517
[19/Nov/2020 22:57:39] "GET /admin/empressa_api/empressa/ HTTP/1.1" 200 4618
[19/Nov/2020 22:57:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[19/Nov/2020 22:59:03] "GET /admin/empressa_api/empressa/add/ HTTP/1.1" 200 6493
[19/Nov/2020 22:59:03] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[19/Nov/2020 23:01:53] "POST /admin/empressa_api/empressa/add/ HTTP/1.1" 302 0
[19/Nov/2020 23:01:53] "GET /admin/empressa_api/empressa/ HTTP/1.1" 200 5045
[19/Nov/2020 23:01:53] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[19/Nov/2020 23:04:23] "GET /admin/empressa_api/empressa/add/ HTTP/1.1" 200 6493
[19/Nov/2020 23:04:23] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[19/Nov/2020 23:08:17] "POST /admin/empressa_api/empressa/add/ HTTP/1.1" 302 0
[19/Nov/2020 23:08:17] "GET /admin/empressa_api/empressa/ HTTP/1.1" 200 5271
[19/Nov/2020 23:08:17] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[20/Nov/2020 09:17:28] "GET / HTTP/1.1" 200 95
[20/Nov/2020 14:04:52] code 400, message Bad request syntax ("\x00\x00\x00àZ\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x05\x01=K\x00\x00\x00\x00j²¨À\x00PVÀ\x00\x01\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000\x81\x89\x02\x81\x81\x00\x8fÁ`ñ.\x9eèå \x03Å\x9e\x98Ñ!ËÏ\\×xöÙ\x8elþyvY\x17\x1cdÅ\x80\x140p\xad\x83Ú·M\x02ÃOËÔ\x85¤¢o¥\x1dSêx$!\x96ö,¯§'\x81\x97\x98°ó,ç\x14E|7\x92Âø\x1fÓ'\x03\x86\x1b9àX\x8bÜ\x16\x01z6_G^¬|¦_=\x8aXfp¤1H¿óR\x90Ràåq³æ£¼·\x1bY#\x92ã0ÈM\x02\x03\x01\x00\x01")
[20/Nov/2020 14:04:52] "   àZ          =K    j²¨À PVÀ                                                  0 Á`ñ.èå ÅÑ!ËÏ\×xöÙlþyvYdÅ0p­Ú·MÃOËÔ¤¢o¥Sêx$!ö,¯§'°ó,çE|7ÂøÓ'9àXÜz6_G^¬|¦_=Xfp¤1H¿óRRàåq³æ£¼·Y#ã0ÈM " 400 -
[20/Nov/2020 16:26:36] "GET / HTTP/1.0" 200 99
/usr/lib/python3.5/sqlite3/__init__.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
November 19, 2020 - 22:57:05
Django version 2.2.17, using settings 'api.settings'
Starting development server at http://192.168.168.75:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/usr/lib/python3.5/fnmatch.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
November 20, 2020 - 22:03:19
Django version 2.2.17, using settings 'api.settings'
Starting development server at http://192.168.168.75:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 20, 2020 - 22:03:22
Django version 2.2.17, using settings 'api.settings'
Starting development server at http://192.168.168.75:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[24/Nov/2020 00:41:26] "GET / HTTP/1.1" 200 5518
[24/Nov/2020 00:41:26] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[24/Nov/2020 00:41:26] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[24/Nov/2020 00:41:26] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[24/Nov/2020 00:41:26] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[24/Nov/2020 00:41:26] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[24/Nov/2020 00:41:26] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[24/Nov/2020 00:41:26] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[24/Nov/2020 00:41:26] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[24/Nov/2020 00:41:26] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[24/Nov/2020 00:41:26] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[24/Nov/2020 00:41:26] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[24/Nov/2020 00:41:26] "GET /favicon.ico HTTP/1.1" 404 4090
[24/Nov/2020 01:00:32] "GET / HTTP/1.1" 200 5518
[24/Nov/2020 01:00:32] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[24/Nov/2020 01:00:32] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[24/Nov/2020 01:00:32] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[24/Nov/2020 01:00:32] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[24/Nov/2020 01:00:32] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[24/Nov/2020 01:00:32] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
Not Found: /favicon.ico
[24/Nov/2020 01:00:32] "GET /favicon.ico HTTP/1.1" 404 4090
[24/Nov/2020 01:16:15] "GET /api-auth/login/?next=/ HTTP/1.1" 200 2701
Not Found: /favicon.ico
[24/Nov/2020 01:16:16] "GET /favicon.ico HTTP/1.1" 404 4090
[24/Nov/2020 01:16:23] "POST /api-auth/login/ HTTP/1.1" 200 2941
[24/Nov/2020 01:16:27] "POST /api-auth/login/ HTTP/1.1" 302 0
[24/Nov/2020 01:16:27] "GET / HTTP/1.1" 200 5748
[24/Nov/2020 01:16:37] "GET /admin/ HTTP/1.1" 200 6061
[24/Nov/2020 01:16:38] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[24/Nov/2020 01:16:38] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[24/Nov/2020 01:16:38] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[24/Nov/2020 01:16:38] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[24/Nov/2020 01:16:38] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[24/Nov/2020 01:16:38] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[24/Nov/2020 01:16:38] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[24/Nov/2020 01:16:38] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[24/Nov/2020 01:16:38] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[24/Nov/2020 01:16:50] "GET /admin/rest_framework_api_key/apikey/ HTTP/1.1" 200 4419
[24/Nov/2020 01:16:50] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[24/Nov/2020 01:16:50] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
[24/Nov/2020 01:16:50] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[24/Nov/2020 01:16:50] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[24/Nov/2020 01:16:50] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[24/Nov/2020 01:16:50] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[24/Nov/2020 01:16:50] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[24/Nov/2020 01:16:50] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[24/Nov/2020 01:16:50] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[24/Nov/2020 01:16:50] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[24/Nov/2020 01:16:50] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[24/Nov/2020 01:16:50] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[24/Nov/2020 01:17:01] "GET /admin/rest_framework_api_key/apikey/add/ HTTP/1.1" 200 6021
[24/Nov/2020 01:17:02] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7777
[24/Nov/2020 01:17:02] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[24/Nov/2020 01:17:02] "GET /static/admin/css/forms.css HTTP/1.1" 200 8518
[24/Nov/2020 01:17:02] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20218
[24/Nov/2020 01:17:02] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[24/Nov/2020 01:17:02] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
[24/Nov/2020 01:17:02] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
[24/Nov/2020 01:17:02] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[24/Nov/2020 01:17:02] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[24/Nov/2020 01:17:34] "POST /admin/rest_framework_api_key/apikey/add/ HTTP/1.1" 302 0
[24/Nov/2020 01:17:35] "GET /admin/rest_framework_api_key/apikey/ HTTP/1.1" 200 7616
[24/Nov/2020 01:17:35] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[24/Nov/2020 01:17:35] "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[24/Nov/2020 01:17:36] "GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504
[24/Nov/2020 01:17:36] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[24/Nov/2020 01:17:36] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[24/Nov/2020 01:21:10] "GET / HTTP/1.1" 200 5748
[24/Nov/2020 01:48:07] "GET / HTTP/1.1" 200 123
[24/Nov/2020 04:00:51] "GET / HTTP/1.1" 200 95
[24/Nov/2020 15:31:45] "GET / HTTP/1.1" 200 123
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/opt/app_api_Pi/ambiente/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[24/Nov/2020 15:40:08] "GET / HTTP/1.1" 200 123
[24/Nov/2020 15:40:09] "GET / HTTP/1.1" 200 123
Watching for file changes with StatReloader
[26/Nov/2020 00:54:26] "GET / HTTP/1.1" 200 5518
[26/Nov/2020 00:54:26] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[26/Nov/2020 00:54:26] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[26/Nov/2020 00:54:26] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[26/Nov/2020 00:54:26] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[26/Nov/2020 00:54:26] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[26/Nov/2020 00:54:26] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[26/Nov/2020 00:54:26] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[26/Nov/2020 00:54:26] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[26/Nov/2020 00:54:26] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[26/Nov/2020 00:54:26] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[26/Nov/2020 00:54:27] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[26/Nov/2020 00:54:27] "GET /favicon.ico HTTP/1.1" 404 4090
[26/Nov/2020 13:31:13] "GET / HTTP/1.1" 200 95
[26/Nov/2020 21:52:16] "GET / HTTP/1.0" 200 99
